#ifndef BPS_ACCOUNT_MESSAGE_H
#define BPS_ACCOUNT_MESSAGE_H

#define ACCOUNT_NUMBER_TAG "NA"
#define ACCOUNT_BALANCE_TAG "AB"
#define ACCOUNT_LEDGER_BALANCE_TAG "LB"
#define ACCOUNT_UPDATE_TIME_TAG "UT"

#define ACCOUNT_NUMBER_LENGTH 24
#define ACCOUNT_BALANCE_LENGTH 13
#define ACCOUNT_LEDGER_BALANCE_LENGTH 13
#define ACCOUNT_UPDATE_TIME_LENGTH 19

#endif  // !BPS_ACCOUNT_MESSAGE_H
